version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: custom-jenkins
    ports:
      - "8080:8080"    # Expose Jenkins UI on port 8080
      - "50000:50000"  # Expose port for Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home   # Persistent Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker builds
      - ./k8s:/var/jenkins_home/k8s # Mount Kubernetes configuration files (optional)
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Skip setup wizard (optional)
    user: root # Run as root to allow installing dependencies
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y curl docker.io git maven &&
      curl -LO https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz &&
      tar -xvf jdk-21_linux-x64_bin.tar.gz -C /opt &&
      rm jdk-21_linux-x64_bin.tar.gz &&
      update-alternatives --install /usr/bin/java /usr/bin/java /opt/jdk-21/bin/java 1 &&
      update-alternatives --install /usr/bin/javac /usr/bin/javac /opt/jdk-21/bin/javac 1 &&
      echo 'export JAVA_HOME=/opt/jdk-21' >> /etc/profile.d/jdk21.sh &&
      source /etc/profile.d/jdk21.sh &&
      curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.26.0/bin/linux/amd64/kubectl &&
      chmod +x kubectl &&
      mv kubectl /usr/local/bin/ &&
      jenkins-plugin-cli --plugins 'docker-workflow kubernetes pipeline-maven' &&
      exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "

volumes:
  jenkins_home:
